# -*- coding: utf-8 -*-
"""CIE - 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VaitOs8uZULtbJmCYHvlNlI3mFSlMynf
"""

import pandas as pd
data = pd.read_csv("/content/titanic.csv")
print(data)

data.describe()

data.head(5)

data.info()

data.isnull().sum()

data.duplicated()

data.shape

data.dtypes

data['Pclass'].unique()

import numpy as np
from scipy import stats
mean = np.mean(data['Age'])
median = np.median(data['Age'])
mode = stats.mode(data['Age'],keepdims=True).mode[0]
mean1 = np.mean(data['Fare'])
median1 = np.median(data['Fare'])
mode1 = stats.mode(data['Fare'],keepdims=True).mode[0]
print(mean)
print(mode)
print(median)
print(mean1)
print(mode1)
print(median1)

import pandas as pd
import matplotlib.pyplot as plt
data['Survived'] = data['Survived'].replace({1: 'survived', 0: 'not survived'})
print(data['Survived'])
grouped_data = data.groupby(['Survived', 'Pclass']) ['PassengerId']. count().unstack()
grouped_data.plot(kind='bar', figsize=(10, 6))
plt.title('Survival Counts by Pclass')
plt.xlabel('Survival')
plt.ylabel('Count')
plt.xticks ( ticks=[0, 1], labels=['0', '1'],rotation=0)
plt.legend(title='Pclass')
plt.show()

null_values = data.isnull().sum()
filled_df = data.fillna(data.mean(numeric_only=True))
null_values, filled_df.head()

import numpy as np
mean = np.mean(data['Age'])
std=np.std(data['Age'])
print('mean of the dataset is',mean)
print('std. deviation is',std)

threshold = 3
outlier = []
for i in data['Age']:
  z=(i-mean)/std
  if z> threshold:
    outlier.append(i)
print( outlier)

import seaborn as sns
sns.boxplot(data['Age'])